name: giveaway
version: '${version}'
main: blestit.giveaway.Giveaway
api-version: 1.16
authors: [Blestit]
description: plugin
commands:
  startgiveaway:
    description: Start a giveaway
    usage: /<command>